In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow import keras
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split ,KFold,RandomizedSearchCV,GridSearchCV,cross_val_score
%matplotlib inline

In [2]:
df= pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.sample(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5058,1376-HHBDV,Female,0,No,No,30,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,48.80,1536.75,No
1787,7789-HKSBS,Female,1,Yes,No,42,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,One year,Yes,Bank transfer (automatic),105.20,4599.15,No
6255,4476-OSWTN,Male,1,Yes,No,69,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,110.55,7610.1,No
6519,4184-VODJZ,Male,0,Yes,Yes,63,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,One year,Yes,Electronic check,91.35,5764.7,No
2739,4455-BFSPD,Female,0,Yes,No,61,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Yes,One year,No,Bank transfer (automatic),101.15,6383.9,No
6056,8331-ZXFOE,Female,0,No,No,58,Yes,Yes,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Credit card (automatic),71.10,4299.2,No
4647,7396-VJUZB,Male,0,Yes,Yes,4,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,No,Mailed check,45.25,155.35,No
6782,1596-OQSPS,Female,0,No,No,11,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,51.10,531.15,No
6567,6215-NQCPY,Male,0,No,No,15,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.70,1566.75,No
4006,2607-DHDAK,Male,0,Yes,Yes,72,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),19.80,1414.65,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df.drop('customerID',axis='columns',inplace=True)

In [5]:
df['TotalCharges']=pd.to_numeric(df.TotalCharges,errors='coerce')

In [6]:
df[df['TotalCharges'].isnull()]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [7]:
df=df[df.TotalCharges!=' ']
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [8]:
#check for no of unique columns

for name in df.columns:
    if df[name].dtypes=='object':
        unique_values = df[name].unique()
        print(f"Feature '{name}' has '{unique_values}' unique values")

Feature 'gender' has '['Female' 'Male']' unique values
Feature 'Partner' has '['Yes' 'No']' unique values
Feature 'Dependents' has '['No' 'Yes']' unique values
Feature 'PhoneService' has '['No' 'Yes']' unique values
Feature 'MultipleLines' has '['No phone service' 'No' 'Yes']' unique values
Feature 'InternetService' has '['DSL' 'Fiber optic' 'No']' unique values
Feature 'OnlineSecurity' has '['No' 'Yes' 'No internet service']' unique values
Feature 'OnlineBackup' has '['Yes' 'No' 'No internet service']' unique values
Feature 'DeviceProtection' has '['No' 'Yes' 'No internet service']' unique values
Feature 'TechSupport' has '['No' 'Yes' 'No internet service']' unique values
Feature 'StreamingTV' has '['No' 'Yes' 'No internet service']' unique values
Feature 'StreamingMovies' has '['No' 'Yes' 'No internet service']' unique values
Feature 'Contract' has '['Month-to-month' 'One year' 'Two year']' unique values
Feature 'PaperlessBilling' has '['Yes' 'No']' unique values
Feature 'PaymentMethod' has '['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']' unique values
Feature 'Churn' has '['No' 'Yes']' unique values

In [9]:
df.replace('No internet service','No',inplace=True)
df.replace('No phone service','No',inplace=True)

In [10]:
le= LabelEncoder()

columns=['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup',
         'DeviceProtection','TechSupport','StreamingTV','Contract',
         'PaperlessBilling','PaymentMethod','Churn','StreamingMovies']

for item in columns:
        df[item] = le.fit_transform(df[item])

In [11]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,1,0,1,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,1,1,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,0,0,1,0,1,1,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,0,1,0,1,1,1,1,1,1,3,84.80,1990.50,0
7039,0,0,1,1,72,1,1,1,0,1,1,0,1,1,1,1,1,103.20,7362.90,0
7040,0,0,1,1,11,0,0,0,1,0,0,0,0,0,0,1,2,29.60,346.45,0
7041,1,1,1,0,4,1,1,1,0,0,0,0,0,0,0,1,3,74.40,306.60,1
7042,1,0,0,0,66,1,0,1,1,0,1,1,1,1,2,1,0,105.65,6844.50,0

In [12]:
X  = df.drop(columns=[ 'Churn'])
y=df.Churn

In [13]:
scaler = StandardScaler()
X=scaler.fit_transform(X)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=88)

In [15]:
X_train.shape

(4930, 19)

In [16]:
model=keras.Sequential([
    keras.layers.Dense(13,input_shape=(19,),activation='relu'),  
    keras.layers.Dense(1,activation='sigmoid')        
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']
             )

model.fit(X_train,y_train,epochs=5)

Epoch 1/5
155/155 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.7306
Epoch 2/5
155/155 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7367
Epoch 3/5
155/155 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7367
Epoch 4/5
155/155 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7367
Epoch 5/5
155/155 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7367

In [17]:
model.evaluate(X_test,y_test)

67/67 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7298

[nan, 0.7297680974006653]

In [18]:
pred=model.predict(X_test)

67/67 [==============================] - 0s 2ms/step